config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", :as => "rate"
  resources :books do
    collection do
      get :search
      get :most_popular
      get :highest_rated
      get :most_recent
    end

    member do
      get :add_to_cart
      get :remove_from_cart
    end

    resources :comments
  end
  resources :authors
  resources :categories
  namespace :admin do
    devise_for :users, ActiveAdmin::Devise.config
  end
  resources :comments
  resources :carts, only: [:index]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get :stop_impersonating, on: :collection
  end
  ActiveAdmin.routes(self)
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books 

  validates :name, presence: true
  
  searchkick searchable: [:name]
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  ratyrate_rateable 'stars'

  mount_uploader :picture, PictureUploader

  searchkick searchable: [:name]
  
  belongs_to :category
  has_and_belongs_to_many :authors
  has_many :comments

  serialize :authors

  validates :name, presence: true

  def has_rates?
    self.stars_rates.present?
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  alias_attribute :books, :carted_books

  has_many :carted_books
  belongs_to :user

  def has_book?(book)
    self.books.find_by(book_id: book.id).present?
  end

  def total_price
    total = 0
    self.books.each do |entry|
      total += entry.total_price
    end
    total
  end

  def total_amount
    self.books.pluck(:amount).sum
  end
end

app/models/carted_book.rb
class CartedBook < ApplicationRecord
  belongs_to :book

  def total_price
    self.amount * self.book.price
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :book
  belongs_to :user

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role, :create_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  ratyrate_rater

  mount_uploader :avatar, AvatarUploader
  has_one :cart
  has_many :books, through: :cart
  has_many :comments

  action_store :like, :comment, counter_cache: true

  validates :avatar, file_size: {less_than: 2.megabytes}
  validates :name, presence: true
  validates :email, presence: true

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  def admin?
    self.has_role? :admin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @most_popular = Book.includes(:authors).first(4)
    @most_recent = Book.includes(:authors).offset(4).first(4)
    @highest_rated = Book.includes(:authors).last(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def meta_description(page_meta_description)
    content_for(:meta_description) { page_meta_description }
  end

  def heading(page_heading)
    content_for(:heading) { page_heading }
  end

  def humanize_boolean(input)
    input ||= ''
    case input.to_s.downcase
    when 't', 'true'
      'Yes'
    else
      'No'
    end
  end

  def css_for_boolean(input)
    if input
      'success'
    else
      'danger'
    end
  end

  def comment_button_text(count)
    if count == 0
      'No Comments'
    elsif count == 1
      '1 Comment'
    else
      "#{count} Comments"
    end
  end

  def flash_key(key)
    if key == 'alert'
      'danger'
    elsif key == 'notice'
      'primary'
    else
      key
    end
  end

  def avatar_url(avatar)
    if avatar.present?
      avatar.url
    else
      'http://via.placeholder.com/200x200'
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.haml
.uk-flex.uk-flex-around
  .uk-text-primary.uk-text-bold Most popular
  .uk-text-primary.uk-text-bold
    = link_to 'See more', most_popular_books_path
.uk-grid.uk-grid-match{:class => "uk-child-width-1-4@m", "uk-grid" => ""}
  - @most_popular.each do |book|
    %div
      .uk-card.uk-card-default.book-card
        .uk-card-media-top
          = link_to book_path(book) do
            %img{:alt => "", :src => "#{book.picture.url}"}/
        .uk-card-body
          = link_to book_path(book) do
            %h3.uk-card-title= book.name
          %p= "By #{book.authors.pluck(:name).join(', ')}"
          %p= book.description.truncate(80, separator: ' ') if book.description.present?
%hr
.uk-flex.uk-flex-around
  .uk-text-primary.uk-text-bold Most recent
  .uk-text-primary.uk-text-bold
    = link_to 'See more', most_recent_books_path
.uk-grid.uk-grid-match{:class => "uk-child-width-1-4@m", "uk-grid" => ""}
  - @most_recent.each do |book|
    %div
      .uk-card.uk-card-default.book-card
        .uk-card-media-top
          = link_to book_path(book) do
            %img{:alt => "", :src => "#{book.picture.url}"}/
        .uk-card-body
          = link_to book_path(book) do
            %h3.uk-card-title= book.name
          %p= "By #{book.authors.pluck(:name).join(', ')}"
          %p= book.description.truncate(80, separator: ' ') if book.description.present?
%hr
.uk-flex.uk-flex-around
  .uk-text-primary.uk-text-bold Highest rated
  .uk-text-primary.uk-text-bold
    = link_to 'See more', highest_rated_books_path
.uk-grid.uk-grid-match{:class => "uk-child-width-1-4@m", "uk-grid" => ""}
  - @highest_rated.each do |book|
    %div
      .uk-card.uk-card-default.book-card
        .uk-card-media-top
          = link_to book_path(book) do
            %img{:alt => "", :src => "#{book.picture.url}"}/
        .uk-card-body
          = link_to book_path(book) do
            %h3.uk-card-title= book.name
          %p= "By #{book.authors.pluck(:name).join(', ')}"
          %p= book.description.truncate(80, separator: ' ') if book.description.present?