config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", :as => "rate"
  resources :books do
    collection do
      get :search
      get :most_popular
      get :highest_rated
      get :most_recent
    end

    member do
      get :add_to_cart
      get :remove_from_cart
    end

    resources :comments
  end
  resources :authors
  resources :categories
  namespace :admin do
    devise_for :users, ActiveAdmin::Devise.config
  end
  resources :comments
  resources :carts, only: [:index]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get :stop_impersonating, on: :collection
  end
  ActiveAdmin.routes(self)
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books 

  validates :name, presence: true
  
  searchkick searchable: [:name]
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  ratyrate_rateable 'stars'

  mount_uploader :picture, PictureUploader

  searchkick searchable: [:name]
  
  belongs_to :category
  has_and_belongs_to_many :authors
  has_many :comments

  serialize :authors

  validates :name, presence: true

  def has_rates?
    self.stars_rates.present?
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  alias_attribute :books, :carted_books

  has_many :carted_books
  belongs_to :user

  def has_book?(book)
    self.books.find_by(book_id: book.id).present?
  end

  def total_price
    total = 0
    self.books.each do |entry|
      total += entry.total_price
    end
    total
  end

  def total_amount
    self.books.pluck(:amount).sum
  end
end

app/models/carted_book.rb
class CartedBook < ApplicationRecord
  belongs_to :book

  def total_price
    self.amount * self.book.price
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :book
  belongs_to :user

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role, :create_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  ratyrate_rater

  mount_uploader :avatar, AvatarUploader
  has_one :cart
  has_many :books, through: :cart
  has_many :comments

  action_store :like, :comment, counter_cache: true

  validates :avatar, file_size: {less_than: 2.megabytes}
  validates :name, presence: true
  validates :email, presence: true

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  def admin?
    self.has_role? :admin
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index; end

  def search
    @books = Book.search(params[:search], fields: [:name], misspellings: {below: 10}, includes: [:authors]).results
  end

  def show
    @book = Book.find(params[:id])
    @book.click = 0 unless @book.click.present?
    count = @book.click + 1
    @book.update_attributes(click: count)
  end

  def add_to_cart
    book = Book.find(params[:id])
    if !current_user.cart.present?
      cart = Cart.new
      cart.user = current_user
      cart.save!
    end
    CartActions::AddBookToCart.new(current_user.cart, book).call
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: "#{book.name} was added to the cart" }
    end
  end

  def remove_from_cart
    book = Book.find(params[:id])
    text = ''
    if params[:all]
      CartActions::RemoveBookFromCart.new(current_user.cart, book, true).call
      text = "All #{book.name} were removed from the cart"
    else
      CartActions::RemoveBookFromCart.new(current_user.cart, book).call
      text = "#{book.name} was removed from the cart"
    end
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: text }
    end
  end

  def most_popular
    @books = Book.all.order(:click).page params[:page]
  end

  def highest_rated
    #! ass performance, this is like REALLY bad
    @books = Kaminari.paginate_array(Book.all.select(&:has_rates?).first(30).sort_by { |b| -b.stars_average.avg }).page params[:page]
  end

  def most_recent
    @books = Book.all.order(:created_at).page params[:page]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @most_popular = Book.includes(:authors).first(4)
    @most_recent = Book.includes(:authors).offset(4).first(4)
    @highest_rated = Book.includes(:authors).last(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def meta_description(page_meta_description)
    content_for(:meta_description) { page_meta_description }
  end

  def heading(page_heading)
    content_for(:heading) { page_heading }
  end

  def humanize_boolean(input)
    input ||= ''
    case input.to_s.downcase
    when 't', 'true'
      'Yes'
    else
      'No'
    end
  end

  def css_for_boolean(input)
    if input
      'success'
    else
      'danger'
    end
  end

  def comment_button_text(count)
    if count == 0
      'No Comments'
    elsif count == 1
      '1 Comment'
    else
      "#{count} Comments"
    end
  end

  def flash_key(key)
    if key == 'alert'
      'danger'
    elsif key == 'notice'
      'primary'
    else
      key
    end
  end

  def avatar_url(avatar)
    if avatar.present?
      avatar.url
    else
      'http://via.placeholder.com/200x200'
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.haml
%ul.uk-comment-list
  - books.each do |book|
    = render 'books/tile', book: book

app/views/books/_tile.haml
%li
  %article.uk-comment.uk-visible-toggle
    %header.uk-comment-header.uk-position-relative
      .uk-grid-medium.uk-flex-middle.uk-grid{"uk-grid" => ""}
        .uk-width-auto.uk-first-column
          = link_to book_path(book) do
            %img.uk-comment-avatar{:alt => "", :height => "125", :src => "#{book.picture.url}", :width => "88"}
        .uk-width-expand
          %h4.uk-comment-title.uk-margin-remove
            = link_to book.name, book_path(book.id), class: 'uk-link-reset'
          %p.uk-comment-meta.uk-margin-remove-top
            %a.uk-link-reset= "By #{book.authors.pluck(:name).join(', ')}"
          - if book.has_rates?
            = rating_for book, 'stars', enable_half: true, disable_after_rate: true, imdb_avg: true
    .uk-comment-body
      %p= book.description.truncate(250, separator: ' ') if book.description.present?
      %ul.uk-subnav.uk-subnav-divider{"uk-margin" => ""}
        %li.uk-first-column
          = link_to 'Read more', book_path(book.id), class: 'uk-text-primary'
        %li
          %a.uk-text-success{:href => "#"} Add to cart
        - if current_user
          - if current_user.cart.has_book? book
            %li
              = fa_icon 'shopping-cart', 'uk-tooltip': 'title: Already in cart'

app/views/books/highest_rated.haml
%h2.uk-h3 Highest Rated
%hr
= render 'books/list', books: @books
= paginate @books
                

app/views/books/index.haml
#books
            

app/views/books/most_popular.haml
%h2.uk-h3 Most Popular
%hr
= render 'books/list', books: @books
= paginate @books
                

app/views/books/most_recent.haml
%h2.uk-h3 Most Recent
%hr
= render 'books/list', books: @books
= paginate @books
                

app/views/books/search.haml
%h2.uk-h3 Book Search
%hr
= render 'books/list', books: @books

app/views/books/show.haml
%article.uk-article
  %h1.uk-article-title
    %p.uk-h4= @book.name
  %img.uk-align-left.uk-margin-remove-adjacent{src: "#{@book.picture.url}", width: "88", height: "125"}
  %p.uk-article-meta
    Written by
    %a{:href => "#"}= @book.authors.pluck(:name).join(', ')
  = rating_for @book, 'stars', enable_half: true, disable_after_rate: true, imdb_avg: true
  %p.book-description= @book.description
  .uk-grid-small.uk-child-width-auto{"uk-grid" => ""}
    %div
      %a.uk-button.uk-button-default{"uk-toggle" => "target: #comments; animation: uk-animation-fade"}= comment_button_text(@book.comments.count)
    - if current_user
      %div
        = link_to 'Add To Cart', add_to_cart_book_path(@book), class: 'uk-button uk-button-success'
      - if current_user.cart.has_book?(@book)
        .uk-inline
          %button.uk-button.uk-button-danger{:type => "button"} Remove From Cart
          %div{"uk-dropdown" => ""}
            %ul.uk-nav.uk-dropdown-nav
              %li.uk-active
                = link_to 'Remove one', remove_from_cart_book_path(@book)
              %li.uk-active
                = link_to 'Remove all', remove_from_cart_book_path(@book, all: true)
%hr
#comments{"hidden": true}
  %ul.uk-comment-list
    - @book.comments.each do |comment|
      %li
        %article.uk-comment.uk-visible-toggle
          %header.uk-comment-header.uk-position-relative
            .uk-grid-medium.uk-flex-middle.uk-grid{"uk-grid" => ""}
              .uk-width-auto.uk-first-column
                %img.uk-comment-avatar{:alt => "", :height => "80", src: "#{comment.user.avatar.url}", :width => "80"}/
              .uk-width-expand.comment-header
                %h4.uk-comment-title.uk-margin-remove
                  %a.uk-link-reset{:href => "#"}= comment.user.name
                %p.uk-comment-meta.uk-margin-remove-top
                  %a.uk-link-reset{:href => "#"}= comment.created_at
          .uk-comment-body
            %p= comment.message
            %ul.uk-subnav.uk-subnav-divider{"uk-margin" => ""}
            - if comment.user == current_user
              %li.uk-first-column
                = link_to 'Delete', comment_path(comment), class: 'uk-text-danger', data: {confirm: 'Are you sure?'}, method: 'delete'
  = simple_form_for([@book, @book.comments.build]) do |f|
    = f.error_notification
    = f.full_error :confirmation_token
    .form-inputs
      = f.label :comment
      = f.input_field :message, required: true, class: 'uk-textarea', rows: '3'
    .form-actions
      .uk-margin
        = f.button :submit, 'Submit'

app/views/shared/books/_tile.haml
%v-flex{ "xs3": "" }
  %a{":href": "bookPath"}
    %v-card.white-text{ "color": "blue-grey darken-4" }
      %v-container{:fluid => "", "grid-list-lg" => ""}
        %v-layout{:row => ""}
          %v-flex{:xs7 => ""}
            %div.white-text
              .headline {{ book.name }}
              .author-name by {{ book.author.name }}
              .book-description {{ book.description }}
              .release-date {{ book.release_date | formatDate }}
          %v-flex{:xs5 => ""}
            %v-card-media{:contain => "", :height => "125px", ":src": "book.picture.url"}