config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", :as => "rate"
  resources :books do
    collection do
      get :search
      get :most_popular
      get :highest_rated
      get :most_recent
    end

    member do
      get :add_to_cart
      get :remove_from_cart
    end

    resources :comments
  end
  resources :authors
  resources :categories
  namespace :admin do
    devise_for :users, ActiveAdmin::Devise.config
  end
  resources :comments
  resources :carts, only: [:index]
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get :stop_impersonating, on: :collection
  end
  ActiveAdmin.routes(self)
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books 

  validates :name, presence: true
  
  searchkick searchable: [:name]
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  ratyrate_rateable 'stars'

  mount_uploader :picture, PictureUploader

  searchkick searchable: [:name]
  
  belongs_to :category
  has_and_belongs_to_many :authors
  has_many :comments

  serialize :authors

  validates :name, presence: true

  def has_rates?
    self.stars_rates.present?
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  alias_attribute :books, :carted_books

  has_many :carted_books
  belongs_to :user

  def has_book?(book)
    self.books.find_by(book_id: book.id).present?
  end

  def total_price
    total = 0
    self.books.each do |entry|
      total += entry.total_price
    end
    total
  end

  def total_amount
    self.books.pluck(:amount).sum
  end
end

app/models/carted_book.rb
class CartedBook < ApplicationRecord
  belongs_to :book

  def total_price
    self.amount * self.book.price
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :book
  belongs_to :user

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role, :create_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  ratyrate_rater

  mount_uploader :avatar, AvatarUploader
  has_one :cart
  has_many :books, through: :cart
  has_many :comments

  action_store :like, :comment, counter_cache: true

  validates :avatar, file_size: {less_than: 2.megabytes}
  validates :name, presence: true
  validates :email, presence: true

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  def admin?
    self.has_role? :admin
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |key, msg|
  - unless key == :timedout
    = content_tag :div, class: "alert alert-dismissable alert-#{key}" do
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}
        ×
      = msg

app/views/layouts/_footer.html.haml
%p.text-muted
  © #{Time.now.year.to_s} Emporium - All rights reserved

app/views/layouts/_google_analytics.html.haml
- if ENV['GOOGLE_ANALYTICS_UA'].present?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    // Enable 'Demographics and interest reports' in your analytics settings
    // ga('require', 'displayfeatures');

    // Enable 'Use enhanced link attribution' in your analytics settings
    // ga('require', 'linkid', 'linkid.js');

    ga('create', '#{ENV["GOOGLE_ANALYTICS_UA"]}', 'auto');
    ga('send', 'pageview');

app/views/layouts/_header.haml
%header.cd-main-header.animate-search#header-app
  %nav.cd-main-nav-wrapper
    %a.cd-search-trigger.cd-text-replace{:href => "#search"} Search
  / .cd-main-nav-wrapper
  %a.cd-nav-trigger.cd-text-replace{:href => "#0"}
    Menu
    %span

app/views/layouts/_menu.haml
%nav.cd-side-nav
  %ul.uk-nav.uk-nav-default
    %li.cd-label= t('menu.main')
    %li{class: "#{controller.controller_name == 'home' ? 'active' : ''}"}
      = link_to root_path do
        = fa_icon 'bars', text: t('menu.start')
    %li.has-children.notifications{class: "#{controller.controller_name == 'books' ? 'active' : ''}"}
      %a{:href => "#"}= fa_icon 'book', text: t('menu.books')
      %ul
        %li{class: "#{controller.action_name == 'most_popular' ? 'active' : ''}"}
          = link_to most_popular_books_path do
            = fa_icon 'fire', text: t('menu.most_popular')
        %li{class: "#{controller.action_name == 'highest_rated' ? 'active' : ''}"}
          = link_to highest_rated_books_path do
            = fa_icon 'thumbs-up', text: t('menu.highest_rated')
        %li{class: "#{controller.action_name == 'most_recent' ? 'active' : ''}"}
          = link_to most_recent_books_path do
            = fa_icon 'star', text: t('menu.most_recent')
    %li{class: "#{controller.controller_name == 'categories' ? 'active' : ''}"}
      = link_to categories_path do
        = fa_icon 'tags', text: t('menu.categories')
    -# %li{class: "#{controller.controller_name == 'authors' ? 'active' : ''}"}
    -#   = link_to authors_path do
    -#     = fa_icon 'users', text: t('menu.authors')

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Emporium', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Test nav item', root_path

app/views/layouts/_search.haml
#search.cd-main-search
  %form
    %input{:placeholder => "Search...", :type => "search", 'v-model': 'search'}/
    .cd-select
      %span in
      %select{:name => "select-category"}
        %option{:value => "all-categories"} all Categories
        %option{:value => "category1"} Category 1
        %option{:value => "category2"} Category 2
        %option{:value => "category3"} Category 3
      %span.selected-value all Categories
  %results{"inline-template": "true", ":results": "results"}
    .cd-search-suggestions
      .news
        %h3 Results
        %ul
          %item{"v-for": "item in results", "inline-template": "true", ":item": "item"}
            %li
              %a.image-wrapper(href="#0")
                %img{alt: "Thumb", ":src": "item.picture.url"}
              %h4
                %a.cd-nowrap{":href": "Routes.book_path(item.id)"} {{ item.name }}
              %h5 by {{ item.author.name }}
              %time {{ item.release_date | formatDate() }}
      / .news
      .quick-links
        %h3 Quick Links
        %ul
          %li
            %a{:href => "#0"} Find a store
          %li
            %a{:href => "#0"} Accessories
          %li
            %a{:href => "#0"} Warranty info
          %li
            %a{:href => "#0"} Support
          %li
            %a{:href => "#0"} Contact us
    / .quick-links
  / .cd-search-suggestions
  %a.close.cd-text-replace{:href => "#0"} Close Form
/ .cd-main-search
.cd-cover-layer

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= yield :title
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,700", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons", :rel => "stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :integrity => "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", :rel => "stylesheet"}/
    
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    -# template
    %link{:href => "/css/theme.css", :rel => "stylesheet"}/
    %link{:href => "/css/nav.css", :rel => "stylesheet"}/
    %link{:href => "/css/style.css", :rel => "stylesheet"}/
    %script{:src => "/js/modernizr.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.18/js/uikit.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.18/js/uikit-icons.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/js-signals/1.0.0/js-signals.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/hasher/1.2.0/hasher.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/crossroads/0.12.2/crossroads.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.6.2/ckeditor.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"}
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Pacifico", :rel => "stylesheet"}/
    %link{:href => "//cdn.jsdelivr.net/jquery.calenstyle/latest/calenstyle.min.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:src => "//cdn.jsdelivr.net/jquery.calenstyle/latest/calenstyle.min.js", :type => "text/javascript"}
    %link{:href => "https://fonts.googleapis.com/css?family=Pacifico", :rel => "stylesheet"}/
    %script{:src => "//cdn.jsdelivr.net/jquery.calenstyle/latest/i18n/calenstyle-i18n.js", :type => "text/javascript"}
    %script{:src => "/js/CalJsonGenerator.js", :type => "text/javascript"}
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/chartist/0.10.1/chartist.min.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/chartist/0.10.1/chartist.min.js", :type => "text/javascript"}
    %script{:src => "//cloud.tinymce.com/stable/tinymce.min.js"}
    -# template end
    %script{:src => "https://unpkg.com/sweetalert/dist/sweetalert.min.js"}

  %body
    %header.cd-main-header
      = link_to 'Emporium', root_path, class: 'cd-logo'
      .cd-search.is-hidden
        %form{:action => "/books/search"}
          %input{placeholder: t('menu.search'), type: 'search', name: 'search'}/
      / cd-search
      %a.cd-nav-trigger{:href => "#"}
        %span
      %nav.cd-nav
        %ul.cd-top-nav
          - if current_user
            %li
              = link_to carts_path do
                %i.fa.fa-shopping-cart.fa-lg
                .uk-position-top-right.uk-overlay.uk-overlay-default
              = render 'carts/dropdown', cart: current_user.cart
            %li.has-children.account
              %a{:href => "#"}
                - if current_user.avatar.present?
                  = image_tag current_user.avatar.url, alt: 'avatar'
                = current_user.name
              %ul
                %li
                  = link_to t('user_actions.my_account'), user_path(current_user)
                %li
                  = link_to t('user_actions.edit_account'), edit_user_path(current_user)
                %li
                  = link_to t('user_actions.logout'), destroy_user_session_path, method: :delete
                - if current_user != true_user
                  %li
                    = link_to 'Stop Impersonating', stop_impersonating_users_path
          - else
            %li
              = link_to t('user_actions.login'), new_user_session_path
    %main.cd-main-content
      = render 'layouts/menu'
      .content-wrapper
        %br/
        %br/
        %div{:id => "page-content-wrapper uk-margin-top"}
          #content.uk-container.uk-container-medium
            - flash.each do |key, value|
              %div{class: "uk-alert-#{flash_key(key)}", "uk-alert" => ""}
                %a.uk-alert-close{"uk-close" => ""}
                %p= value
            = yield
            = insert_paloma_hook
    %script{:src => "/js/jquery.menu-aim.js"}
    %script{:src => "/js/main.js"}